/**
 * Flow Report Generator — produces Markdown reports showing
 * Uploop's advantages over React, Solid, and other frameworks.
 *
 * @module @uploop/flows/report
 */
import { flows } from './registry.js'
import { compareReport } from './strategies.js'

/**
 * Generate a full Markdown report for a given flow + graph.
 *
 * @param {Object} graph — HyperGraph instance
 * @param {string} flowName — flow name from registry
 * @param {Object} [scenario] — { name, description }
 * @returns {string} Markdown report
 */
export function generateReport(graph, flowName, scenario = {}) {
  const flow = flows[flowName]
  if (!flow) throw new Error(`Unknown flow: ${flowName}`)
  const report = compareReport(graph, flow, scenario)

  let md = `# Flow Report: ${flowName}\n\n`
  md += `> **Scenario:** ${scenario.name || 'Benchmark'}\n`
  md += `> **Flow:** ${flow.name} (${flow.category})\n`
  md += `> **Executors:** ${flow.executors.join(' + ')}\n\n`

  md += `## Graph Profile\n\n`
  md += `| Metric | Value |\n|--------|-------|\n`
  md += `| Data nodes | ${report.graphSize.data} |\n`
  md += `| View nodes | ${report.graphSize.views} |\n`
  md += `| Update nodes | ${report.graphSize.updates} |\n`
  md += `| Total nodes | ${report.graphSize.total} |\n\n`

  md += `## Tuning Parameters\n\n`
  md += `| Parameter | Value |\n|-----------|-------|\n`
  for (const [key, value] of Object.entries(flow.tuning)) {
    md += `| ${key} | ${JSON.stringify(value)} |\n`
  }
  md += '\n'

  md += `## Lane Routing\n\n`
  md += `| Pattern | Lane |\n|---------|------|\n`
  for (const [pattern, lane] of Object.entries(flow.lanes)) {
    md += `| \`${pattern}\` | ${lane} |\n`
  }
  md += '\n'

  md += `## Advantages Over Other Frameworks\n\n`
  for (const adv of report.advantages) {
    md += `### ${adv.feature}\n\n`
    md += `| Framework | Approach |\n|-----------|----------|\n`
    md += `| **Uploop** | ${adv.uploop} |\n`
    md += `| React | ${adv.react} |\n`
    md += `| Solid | ${adv.solid} |\n`
    md += `| 🏆 Winner | **${adv.winner}** |\n\n`
  }

  md += `## Performance Estimates\n\n`
  md += `| Metric | Value |\n|--------|-------|\n`
  md += `| View updates per data change | ${report.estimates.viewUpdatesPerChange} |\n`
  md += `| Frame budget | ${report.estimates.frameBudgetUtilization} |\n`
  md += `| Backpressure | ${report.estimates.backpressureMode} |\n`
  md += `| Prefetch enabled | ${report.estimates.prefetchEnabled} |\n\n`

  md += `---\n*Generated by @uploop/flows report generator*\n`
  return md
}

/**
 * Generate a side-by-side comparison of all 24 flows vs React/Solid.
 *
 * @returns {string} Markdown table
 */
export function generateAllFlowsComparison() {
  let md = `# All 24 Flows — Uploop vs React vs Solid\n\n`
  md += `| Flow | Category | Executor(s) | React Approach | Solid Approach | Uploop Advantage |\n`
  md += `|------|----------|-------------|----------------|----------------|------------------|\n`

  for (const [name, flow] of Object.entries(flows)) {
    const execs = flow.executors.join(' + ')
    const reactApproach = frameworkApproach(name, 'react')
    const solidApproach = frameworkApproach(name, 'solid')
    const advantage = flowAdvantage(name)
    md += `| ${name} | ${flow.category} | ${execs} | ${reactApproach} | ${solidApproach} | ${advantage} |\n`
  }

  return md
}

function frameworkApproach(flowName, framework) {
  const map = {
    react: {
      form: 'useState per field + useEffect validation',
      list: 'useState + react-window virtualization',
      chat: 'useEffect + socket.io + manual message queue',
      searchTypeahead: 'useState x3 + useEffect abort + manual debounce',
      dashboard: 'per-widget useEffect, no lane prioritization',
      dataGrid: 'VDOM diff + react-window + tanstack-table',
      realtimeCollab: 'socket.io + manual OT/CRDT lib',
      animation: 'useEffect + requestAnimationFrame, no spring physics',
      aiAgent: 'useEffect + EventSource, setState per token'
    },
    solid: {
      form: 'createSignal per field + createEffect validation',
      list: 'createSignal + For + solid-virtual',
      chat: 'createSignal + socket.io, manual cleanup',
      searchTypeahead: 'createSignal x3 + createEffect + manual abort',
      dashboard: 'per-widget createEffect, equal priority',
      dataGrid: 'createMemo per cell, no formula graph',
      realtimeCollab: 'socket.io + separate signal per op',
      animation: 'createEffect + RAF, manual spring math',
      aiAgent: 'createSignal + EventSource, manual abort'
    }
  }
  return (map[framework] || {})[flowName] || `${framework} generic approach`
}

function flowAdvantage(flowName) {
  const map = {
    form: 'Fine-grained field updates, no whole-form re-render',
    list: 'Edge-based diff — only changed items patch DOM',
    dashboard: 'Mixed executors — chart redraws never block table updates',
    chat: 'Ring buffer backpressure + optimistic send built-in',
    searchTypeahead: 'Debounce, abort, cache all declared on node — 70% less code',
    dataGrid: 'Columnar storage + formula edges = dependency tracking built-in',
    realtimeCollab: 'OT/CRDT ops are graph edges — conflict resolution is an update handler',
    animation: 'Spring physics built into update handler — interruptible by default',
    aiAgent: 'Token streaming via ring buffer + tool calls as ETL pipeline'
  }
  return map[flowName] || 'Graph-driven executor auto-selection'
}
